### ISSUE TITLE
AssignmentExpression support issue

### ISSUE THREAD

**Issue by profiles** [metaes/metaes#28]
AssignmentExpression Interpreter only support '=' operator

not support such as:
`
var a = 1; 
a+=2;
a-=1;
a*=3;
a/=3;
...
`

**Comment by bartosz-k** [comment]
Addressed here: https://github.com/metaes/metaes/commit/07cd02deaa697d452f6670991f542eea3f123d9c.

**Comment by bartosz-k** [comment]
Closing, as mentioned change set will be included in future PR.

**Comment by bartosz-k** [comment]
Thanks, @profiles .
