### ISSUE TITLE
Page not found: http://mitpress.mit.edu/sicp/full-text/sicp/book/node76.html

### ISSUE THREAD

**Issue by ngocdaothanh** [metaes/metaes#5]
The README says:

> As it was said in the prelude, MetaES is a metacircular interpreter. You can learn more about such interpreter for example in SICP book that is available for free online http://mitpress.mit.edu/sicp/full-text/sicp/book/node76.html

But this link is a 404 now.

**Comment by bartq** [comment]
Solved with https://github.com/metaes/metaes/pull/8.
